name: Container Workflow

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: windows-latest
    container:
      image: docker://magicxor/radstudio:xe-delphi-net3.5-ltsc2019

    steps:
      - name: Test unit project
        run: msbuild /t:build ${{ github.repository }}\test\GitActionLoginTest.dproj