name: Container Workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://guillaumefalourd/ritchiecli:go-1.15.8

    steps:
      - name: Run Commands
        run: |
              sudo rit -v
              sudo go version