name: Create Pull Request

on:
  push:
    branches:
      - "develop"

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make changes to pull request
        run: date +%s > DadosNormal.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "auto-pr-branch"
          base: master
          title: [Develop] Atualizacao branch develop
          committer: ${{ github.actor }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          body: |
            Essa são informações de Atualizacao por pull request via actions
          token: ${{ secrets.PAT }}
          delete-branch: true